# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Build

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop, feature/* ]

jobs:
  python-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r prosperity/requirements-prosperity.txt
    - name: Report on code efficiency
      run: |
        python -m radon cc "prosperity/components/sensor.py"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test coverage
      run: |
        pytest --cov="." prosperity/tests
    - name: Test with pytest
      run: |
        pytest

  image-build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.PROSPERITY_CR }}
        username: ${{ secrets.PROSPERITY_CR_USERNAME }}
        password: ${{ secrets.PROSPERITY_CR_PASSWORD }}
    - run: |
        ls -ltr
        docker build . -t ${{ secrets.PROSPERITY_CR }}/prosperity:${{ github.sha }}
        docker push ${{ secrets.PROSPERITY_CR }}/prosperity:${{ github.sha }}
